# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Alister Reis's blog
email: alister.reis@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The blog of a PhD Candidate, former Google Software Engineer, former student of Computer Science/
  Data Science. I'm from Porto Alegre - RS, Brazil. I graduated from both the
  Federal University of Rio Grande do Sul (UFRGS) and the INP Grenoble (ENSIMAG).
  Currently, I'm a PhD Candidate with the Utrecht University.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://amreis.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: machadoalister
github_username:  amreis

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
